---
- name: Deploy RHEL8 VM
  hosts: rhel_app_server
  gather_facts: false

  tasks:
  - name: Create the VM
    vmware_guest:
      datacenter: 'SagelyDC'
      folder: /vm/Demo
      resource_pool: Demo
      name: '{{ inventory_hostname }}'
      state: poweredon
      guest_id: rhel8_64Guest
      annotation: "Test"
      disk:
        - size_gb: 20
          type: thin
          datastore: 'EVO2TB'
      networks:
        - name: DPG-Sandbox
          ip: '{{ ip }}'
          netmask: 255.255.240.0
          gateway: 192.168.16.1
          dns_servers:
            - 192.168.16.1
      hardware:
        memory_mb: 4096
        num_cpus: 2
      customization:
        dns_servers:
          - 192.168.16.1
        domain: demo.toal.ca
        hostname: '{{ inventory_hostname }}'
      template: 'rhel81-x64-v1'
      wait_for_ip_address: true
    delegate_to: localhost
...